import type { ExtractedRow, RunResult } from './types'

// Canned result modeled on samples/01-bank-statements-to-journal-entries/ —
// the shape and rough resolution rate (about half unresolved) echo the real
// numbers documented in that dataset's README.
const rows: ExtractedRow[] = [
  {
    id: 'r1',
    date: '2026-03-03',
    narrative: 'WIRE TRF CALDER PORTFOLIO SVC LLC MGMT FEE Q1',
    counterparty: 'Calder Portfolio Services LLC',
    projectCode: 'PRJ-2201',
    classification: 'Vendor Payment',
    amount: -42500,
    currency: 'EUR',
    matchStatus: 'MATCH',
    confidence_score: 0.94,
    source_document: '20260331_NI_A_B__FUND_II_CALDER_EUR_8102.pdf',
    source_page: 1,
    source_snippet: 'WIRE TRF CALDER PORTFOLIO SVC LLC MGMT FEE Q1  -42,500.00',
  },
  {
    id: 'r2',
    date: '2026-03-04',
    narrative: 'INTL WIRE NORDIC HLDG APS CAPITAL CALL 7',
    counterparty: 'Nordic Holdings ApS',
    projectCode: 'PRJ-3110',
    classification: 'Investment',
    amount: -1250000,
    currency: 'DKK',
    matchStatus: 'MATCH',
    confidence_score: 0.91,
    source_document: '20260331_NI_V_SCSP_CALDER_DKK_0541.pdf',
    source_page: 1,
    source_snippet: 'INTL WIRE NORDIC HLDG APS CAPITAL CALL 7  -1,250,000.00',
  },
  {
    id: 'r3',
    date: '2026-03-05',
    narrative: 'FLD PAY B WESTB ROOK PA RTNERS RE F',
    counterparty: null,
    projectCode: null,
    classification: 'Needs Review',
    amount: -18320.5,
    currency: 'EUR',
    matchStatus: 'UNRESOLVED',
    confidence_score: 0.41,
    source_document: '20260331_NI_A_B__FUND_II_CALDER_EUR_8102.pdf',
    source_page: 2,
    source_snippet: 'FLD PAY B WESTB ROOK PA RTNERS RE F  -18,320.50',
  },
  {
    id: 'r4',
    date: '2026-03-05',
    narrative: 'DIST TO LP INVESTOR ACCT 88213',
    counterparty: 'Investor 88213',
    projectCode: 'PRJ-3110',
    classification: 'Investor Movement',
    amount: -87500,
    currency: 'DKK',
    matchStatus: 'MATCH',
    confidence_score: 0.88,
    source_document: '20260331_NI_V_SCSP_CALDER_DKK_0541.pdf',
    source_page: 2,
    source_snippet: 'DIST TO LP INVESTOR ACCT 88213  -87,500.00',
  },
  {
    id: 'r5',
    date: '2026-03-06',
    narrative: 'PYMT REF PRJ-99XX UNKNOWN LEGACY CODE',
    counterparty: 'Related Fund Entity (unconfirmed)',
    projectCode: null,
    classification: 'Related Party Transfer',
    amount: -6200,
    currency: 'GBP',
    matchStatus: 'FLAGGED',
    confidence_score: 0.52,
    source_document: '20260331_NI_V_SCSP_CALDER_GBP_3252.pdf',
    source_page: 1,
    source_snippet: 'PYMT REF PRJ-99XX UNKNOWN LEGACY CODE  -6,200.00',
  },
  {
    id: 'r6',
    date: '2026-03-07',
    narrative: 'FX SETTLEMENT EUR/USD SPOT CONVERSION',
    counterparty: 'Internal Treasury',
    projectCode: 'PRJ-1000',
    classification: 'Internal',
    amount: 154200,
    currency: 'USD',
    matchStatus: 'MATCH',
    confidence_score: 0.97,
    source_document: '20260331_NI_GMF_II_SCSP_CALDER_USD_4373.pdf',
    source_page: 1,
    source_snippet: 'FX SETTLEMENT EUR/USD SPOT CONVERSION  +154,200.00',
  },
  {
    id: 'r7',
    date: '2026-03-10',
    narrative: 'BEN NM TR UNCATED VDR SVCS GRP',
    counterparty: null,
    projectCode: 'PRJ-2201',
    classification: 'Vendor Payment',
    amount: -3175,
    currency: 'EUR',
    matchStatus: 'UNRESOLVED',
    confidence_score: 0.38,
    source_document: '20260331_NI_ABF_I_SCSP_CALDER_EUR_0894.pdf',
    source_page: 1,
    source_snippet: 'BEN NM TR UNCATED VDR SVCS GRP  -3,175.00',
  },
  {
    id: 'r8',
    date: '2026-03-11',
    narrative: 'CAPITAL CALL FUNDING GMF II TRANCHE 4',
    counterparty: 'GMF II Portfolio Co.',
    projectCode: 'PRJ-4402',
    classification: 'Investment',
    amount: -910000,
    currency: 'USD',
    matchStatus: 'MATCH',
    confidence_score: 0.93,
    source_document: '20260331_NI_GMF_II_SCSP_CALDER_USD_4373.pdf',
    source_page: 2,
    source_snippet: 'CAPITAL CALL FUNDING GMF II TRANCHE 4  -910,000.00',
  },
  {
    id: 'r9',
    date: '2026-03-12',
    narrative: 'SIDE LETTER FEE ADJ RECALC PENDING',
    counterparty: 'Fund Administrator',
    projectCode: 'PRJ-1000',
    classification: 'Needs Review',
    amount: -4400,
    currency: 'GBP',
    matchStatus: 'FLAGGED',
    confidence_score: 0.47,
    source_document: '20260331_NI_V_SCSP_CALDER_GBP_3252.pdf',
    source_page: 2,
    source_snippet: 'SIDE LETTER FEE ADJ RECALC PENDING  -4,400.00',
  },
  {
    id: 'r10',
    date: '2026-03-13',
    narrative: 'ACH DR VDR CODE 4471 OFFICE SVC',
    counterparty: null,
    projectCode: null,
    classification: 'Vendor Payment',
    amount: -890,
    currency: 'EUR',
    matchStatus: 'UNRESOLVED',
    confidence_score: 0.44,
    source_document: '20260331_NI_A_B__FUND_II_CALDER_DKK_4319.pdf',
    source_page: 1,
    source_snippet: 'ACH DR VDR CODE 4471 OFFICE SVC  -890.00',
  },
  {
    id: 'r11',
    date: '2026-03-14',
    narrative: 'WIRE IN INVESTOR SUBSCRIPTION ACCT 55190',
    counterparty: 'Investor 55190',
    projectCode: 'PRJ-3110',
    classification: 'Investor Movement',
    amount: 500000,
    currency: 'EUR',
    matchStatus: 'MATCH',
    confidence_score: 0.9,
    source_document: '20260331_NI_V_SCSP_CALDER_EUR_030041.pdf',
    source_page: 1,
    source_snippet: 'WIRE IN INVESTOR SUBSCRIPTION ACCT 55190  +500,000.00',
  },
  {
    id: 'r12',
    date: '2026-03-14',
    narrative: 'REF CODE ILLEGIBLE PARTIAL OCR MATCH',
    counterparty: null,
    projectCode: null,
    classification: 'Needs Review',
    amount: -1120,
    currency: 'DKK',
    matchStatus: 'UNRESOLVED',
    confidence_score: 0.29,
    source_document: '20260331_NI_A_B__FUND_II_CALDER_DKK_4319.pdf',
    source_page: 2,
    source_snippet: 'REF CODE ILLEGIBLE PARTIAL OCR MATCH  -1,120.00',
  },
]

export const mockResult: RunResult = {
  id: 'run-demo-001',
  generatedAt: new Date().toISOString(),
  summary: {
    totalRows: rows.length,
    matched: rows.filter((r) => r.matchStatus === 'MATCH').length,
    unresolved: rows.filter((r) => r.matchStatus === 'UNRESOLVED').length,
    flagged: rows.filter((r) => r.matchStatus === 'FLAGGED').length,
    documentsProcessed: new Set(rows.map((r) => r.source_document)).size,
  },
  rows,
}
