import type {
  BridgeCapabilities,
  JobResult,
  JobStatus,
  RecordedReplay,
  StartJobResponse,
  WorkspaceAdapter,
  WorkspaceBootstrap,
} from "../workspaceTypes";

export const capabilitiesFixture: BridgeCapabilities = {
  api_version: "ui.v1",
  execution: {
    label: "LOCAL_DETERMINISTIC",
    model_calls: 0,
    browser_commands_executed: false,
  },
  limits: {
    max_files: 40,
    max_file_bytes: 25 * 1024 * 1024,
    max_batch_bytes: 100 * 1024 * 1024,
    max_path_depth: 12,
    max_events_per_job: 100,
  },
  profiles: [{
    profile_id: "journal-entries",
    label: "Journal entry validation",
    description: "Validate bank-statement rows and running-balance links.",
    source: {
      purpose: "SOURCE",
      required: true,
      formats: [{ extension: ".pdf", content_types: ["application/pdf"] }],
    },
    reference: {
      purpose: "REFERENCE",
      required: false,
      max_files: 1,
      formats: [{
        extension: ".xlsx",
        content_types: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
      }],
      tables: [{ name: "accounts", sheet: "Accounts", columns: ["account", "currency"] }],
    },
  }],
  artifacts: {
    json: { available: true },
    report: { available: false, reason: "The backend does not generate a report." },
    workbook: { available: false, reason: "The backend does not generate a workbook." },
  },
  review_statuses: ["UNREVIEWED", "REVIEWED", "NEEDS_FOLLOW_UP"],
};

export const bootstrapFixture: WorkspaceBootstrap = {
  connection: {
    state: "CONNECTED",
    label: "Backend connected",
    detail: "LOCAL_DETERMINISTIC · 0 model calls",
  },
  profiles: [{
    id: "journal-entries",
    label: "Journal entry validation",
    description: "Validate bank-statement rows and running-balance links.",
    documents: "Bank statement PDFs",
    tables: ["accounts"],
    passes: ["parse", "verify"],
    envelope: ["documents", "findings"],
  }],
  capabilities: capabilitiesFixture,
  replays: [{
    replay_id: "replay-batch-7",
    kind: "RECORDED_REPLAY",
    original_batch_id: "batch-7",
    profile_id: "journal-entries",
    original_run_ids: ["run-a"],
    recorded_seconds: 14,
    model_calls: 0,
    event_trace_available: false,
    links: { self: "/api/ui/v1/replays/replay-batch-7" },
  }],
  issues: [],
};

export const startFixture: StartJobResponse = {
  job_id: "job-123",
  profile_id: "journal-entries",
  case_name: "September statements",
  execution_label: "LOCAL_DETERMINISTIC",
  processing_state: "QUEUED",
  idempotency_reused: false,
  links: {
    status: "/api/ui/v1/jobs/job-123",
    result: "/api/ui/v1/jobs/job-123/result",
  },
};

export const processingJobFixture: JobStatus = {
  job_id: "job-123",
  profile_id: "journal-entries",
  case_name: "September statements",
  execution_label: "LOCAL_DETERMINISTIC",
  processing_state: "PROCESSING",
  created_at: "2026-09-05T10:00:00Z",
  started_at: "2026-09-05T10:00:01Z",
  documents: [{
    source_id: "source-1",
    client_file_id: "client-1",
    relative_path: "statements/operating.pdf",
    filename: "operating.pdf",
    purpose: "SOURCE",
    processing_state: "PROCESSING",
    computational_outcome: null,
  }],
  events: [{
    kind: "tool",
    label: "parse_statement",
    detail: "Parsing operating.pdf",
    status: "running",
    body: "",
    meta: { event_type: "SOURCE_STARTED", sequence: 1, source_id: "source-1" },
    at: 1788602401,
  }],
  event_trace: { bounded: true, max_events: 100, truncated: false },
  links: { result: "/api/ui/v1/jobs/job-123/result" },
};

export const completedJobFixture: JobStatus = {
  ...processingJobFixture,
  processing_state: "SUCCEEDED",
  completed_at: "2026-09-05T10:00:03Z",
  documents: processingJobFixture.documents.map((document) => ({
    ...document,
    processing_state: "SUCCEEDED",
    computational_outcome: "FAIL",
  })),
  events: [
    ...processingJobFixture.events,
    {
      kind: "state",
      label: "completed",
      detail: "Deterministic verification complete",
      status: "ok",
      body: "",
      meta: { event_type: "JOB_COMPLETED", sequence: 2 },
      at: 1788602403,
    },
  ],
};

export const resultFixture: JobResult = {
  job_id: "job-123",
  profile_id: "journal-entries",
  case_name: "September statements",
  execution_label: "LOCAL_DETERMINISTIC",
  processing_state: "SUCCEEDED",
  summary: {
    documents_total: 1,
    documents_succeeded: 1,
    documents_failed: 0,
    checks: { PASS: 1, FAIL: 1, UNRESOLVED: 1 },
    transaction_links: { PASS: 0, FAIL: 1 },
  },
  reference_validation: { status: "NOT_PROVIDED", tables: [] },
  agent_resolution: {
    status: "NOT_RUN",
    reason: "Agent resolution was not requested; deterministic parser and verifier output only.",
  },
  documents: [{
    source_id: "source-1",
    client_file_id: "client-1",
    relative_path: "statements/operating.pdf",
    filename: "operating.pdf",
    purpose: "SOURCE",
    processing_state: "SUCCEEDED",
    computational_outcome: "FAIL",
    statement: {
      account_short_code: "OP-01",
      account_name: "Operating account",
      account_number: "00001234",
      currency: "GBP",
      bank_name: "Example Bank",
      date_range: "2026-08-01 to 2026-08-31",
      closing_balance: "1000.00",
      row_count: 2,
    },
    rows: [{
      row_id: "row-newer",
      index: 0,
      bank_reference: "REF-NEW",
      narrative: "Investor subscription",
      value_date: "2026-08-31",
      credit: "125.00",
      debit: null,
      balance: "1000.00",
      citation: {
        source_id: "source-1",
        filename: "operating.pdf",
        page: 3,
        bbox: { x0: 42.4, top: 100.1, x1: 515.6, bottom: 118.9 },
      },
    }, {
      row_id: "row-older",
      index: 1,
      bank_reference: "REF-OLD",
      narrative: "Earlier balance",
      value_date: "2026-08-30",
      credit: null,
      debit: null,
      balance: "860.00",
      citation: {
        source_id: "source-1",
        filename: "operating.pdf",
        page: 3,
        bbox: { x0: 42.4, top: 120.1, x1: 515.6, bottom: 138.9 },
      },
    }],
    transaction_links: [{
      finding_id: "finding-link-1",
      link_id: "link-1",
      newer_row_id: "row-newer",
      older_row_id: "row-older",
      status: "FAIL",
      balance: "1000.00",
      signed_movement: "125.00",
      derived_balance: "875.00",
      comparison_balance: "860.00",
      difference: "15.00",
      citations: {
        balance: {
          source_id: "source-1",
          filename: "operating.pdf",
          page: 3,
          bbox: { x0: 42.4, top: 100.1, x1: 515.6, bottom: 118.9 },
        },
        comparison_balance: {
          source_id: "source-1",
          filename: "operating.pdf",
          page: 3,
          bbox: { x0: 42.4, top: 120.1, x1: 515.6, bottom: 138.9 },
        },
      },
      review_status: "UNREVIEWED",
    }],
    checks: [{
      finding_id: "finding-check-1",
      name: "date_sequence",
      scope: "document",
      status: "UNRESOLVED",
      detail: "A date sequence could not be verified.",
      evidence: "source rows 1-2",
      review_status: "UNREVIEWED",
    }, {
      finding_id: "finding-check-2",
      name: "account_identity",
      scope: "document",
      status: "PASS",
      detail: "Account identity is internally consistent.",
      evidence: "OP-01",
      review_status: "UNREVIEWED",
    }],
  }],
  findings: [{
    finding_id: "finding-link-1",
    kind: "TRANSACTION_LINK",
    source_id: "source-1",
    status: "FAIL",
    review_status: "UNREVIEWED",
    title: "Running-balance link",
    detail: "The prior balance differs from the derived balance.",
    evidence: "1000.00 - 125.00 = 875.00; comparison 860.00",
  }, {
    finding_id: "finding-check-1",
    kind: "CHECK",
    source_id: "source-1",
    status: "UNRESOLVED",
    review_status: "UNREVIEWED",
    title: "Date sequence",
    detail: "A date sequence could not be verified.",
    evidence: "source rows 1-2",
  }, {
    finding_id: "finding-check-2",
    kind: "CHECK",
    source_id: "source-1",
    status: "PASS",
    review_status: "UNREVIEWED",
    title: "Account identity",
    detail: "Account identity is internally consistent.",
    evidence: "OP-01",
  }],
  profile_projection: { status: "OMITTED", reason: "No profile-specific projection was generated." },
  artifacts: [{
    artifact_id: "result-json",
    kind: "RESULT_JSON",
    filename: "job-123-result.json",
    content_type: "application/json",
    url: "/api/ui/v1/jobs/job-123/artifacts/result-json",
  }],
};

export const replayFixture: RecordedReplay = {
  replay_id: "replay-batch-7",
  kind: "RECORDED_REPLAY",
  original_batch_id: "batch-7",
  profile_id: "journal-entries",
  original_run_ids: ["run-a"],
  recorded_seconds: 14,
  model_calls: 0,
  event_trace_available: false,
  links: { self: "/api/ui/v1/replays/replay-batch-7" },
  accounts: [{
    account: "Operating account",
    run_id: "run-a",
    accepted: true,
    attempts: 1,
    seconds: 14,
    envelope: {
      statement_rows: [{
        row_id: "replay-row-1",
        source_file: "operating.pdf",
        source_page: 1,
        transaction_date: "2026-08-31",
        raw_narrative: "Subscription received",
        amount: "125.00",
        counterparty_status: "MATCHED",
        project_code_status: "MATCHED",
        classification: "Subscription",
      }],
    },
  }],
  timing: { mode: "RECORDED_SECONDS", compression_performed: false },
  note: "Committed example result; no processing was performed while viewing this replay.",
};

export function makeAdapter(overrides: Partial<WorkspaceAdapter> = {}): WorkspaceAdapter {
  return {
    mode: "live",
    bootstrap: async () => bootstrapFixture,
    startJob: async () => startFixture,
    getJob: async () => processingJobFixture,
    getResult: async () => resultFixture,
    updateFindingReview: async (jobId, findingId, reviewStatus) => ({
      job_id: jobId,
      finding_id: findingId,
      status: resultFixture.findings.find((finding) => finding.finding_id === findingId)?.status ?? "UNRESOLVED",
      review_status: reviewStatus,
      updated_at: "2026-09-05T10:01:00Z",
    }),
    getReplay: async () => replayFixture,
    sourceUrl: (jobId, sourceId) => `/api/ui/v1/jobs/${jobId}/sources/${sourceId}`,
    artifactUrl: (jobId, artifactId) => `/api/ui/v1/jobs/${jobId}/artifacts/${artifactId}`,
    ...overrides,
  };
}
